// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0bVuIBsA62zhkZjbHTL7hvyK9B44LaU',
    appId: '1:537633957982:web:ce917359868f8aa7bdeccf',
    messagingSenderId: '537633957982',
    projectId: 'basedat',
    authDomain: 'basedat-87a71.firebaseapp.com',
    storageBucket: 'basedat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXxopNygTHKiLd8Tvo84TA15oxAppFCgo',
    appId: '1:537633957982:android:7a9e0c4976edb4ecbdeccf',
    messagingSenderId: '537633957982',
    projectId: 'basedat',
    storageBucket: 'basedat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMkK-1SB8YflcAdJHjNxKzjhzrosI5ZP8',
    appId: '1:537633957982:ios:0ccebd5d4dfc5564bdeccf',
    messagingSenderId: '537633957982',
    projectId: 'basedat',
    storageBucket: 'basedat.firebasestorage.app',
    iosBundleId: 'com.example.homepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMkK-1SB8YflcAdJHjNxKzjhzrosI5ZP8',
    appId: '1:537633957982:ios:0ccebd5d4dfc5564bdeccf',
    messagingSenderId: '537633957982',
    projectId: 'basedat',
    storageBucket: 'basedat.firebasestorage.app',
    iosBundleId: 'com.example.homepage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo0bVuIBsA62zhkZjbHTL7hvyK9B44LaU',
    appId: '1:537633957982:web:4c428afddf3d8603bdeccf',
    messagingSenderId: '537633957982',
    projectId: 'basedat',
    authDomain: 'basedat-87a71.firebaseapp.com',
    storageBucket: 'basedat.firebasestorage.app',
  );
}
